import { expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { getDb } from "@/lib/db";
import { listGroupStudents, listStudentGroups } from "@/lib/groups/repository";
import { addStudentToTeacherSubject, listTeacherStudents } from "@/lib/students/repository";
import { importTeacherStudents } from "@/lib/students/import-repository";
import { createLesson } from "@/lib/lessons/create";
import { listTeacherLessons } from "@/lib/lessons/repository";
import { listJournalLessons, listJournalStudents, saveAttendance } from "@/lib/attendance/repository";
import { getDateKeyInTimeZone } from "@/lib/schedule-week/rules";
import { endSemester } from "@/lib/semesters/repository";
import { listLessonTypes } from "@/lib/lesson-types/repository";

it.skipIf(!process.env.VIDMITKA_ATTENDANCE_TEST_SCHEMA)("група → студент → власний список заняття → журнал", async () => {
  const sql = getDb();
  const [scope] = await sql`SELECT current_schema() AS name` as unknown as { name: string }[];
  expect(scope.name).toBe(process.env.VIDMITKA_ATTENDANCE_TEST_SCHEMA);
  expect(scope.name).toMatch(/^codex_attendance_test_[0-9a-f]{16}$/u);
  const date = getDateKeyInTimeZone(new Date());
  const weekday = new Date(`${date}T12:00:00Z`).getUTCDay() || 7;
  await sql`INSERT INTO schedule_week_settings (id, anchor_date, anchor_week_type) VALUES (1, ${date}::DATE, 'numerator')`;
  const subjects = await sql`SELECT id::TEXT AS id, name FROM subjects` as unknown as { id: string; name: string }[];
  const programming = subjects.find((subject) => subject.name === "Основи програмування")!.id;
  const math = subjects.find((subject) => subject.name === "Математика")!.id;
  const rooms = await sql`SELECT id::TEXT AS id, name FROM rooms` as unknown as { id: string; name: string }[];
  const periods = await sql`SELECT id::TEXT AS id FROM class_periods ORDER BY number` as unknown as { id: string }[];
  const studentInput = { teacherUserId: "teacher", fullName: "Ковальчук Анна", groupMode: "new", existingGroupName: null, newGroupName: " КН-31 ", subjectId: math, subgroup: "1" };
  expect((await addStudentToTeacherSubject(studentInput)).success).toBe(true);
  expect((await addStudentToTeacherSubject({ ...studentInput, teacherUserId: "other-teacher", fullName: "Мельник Богдан", groupMode: "existing", existingGroupName: "КН-31", newGroupName: "не має створитися", subjectId: programming })).success).toBe(true);
  expect((await addStudentToTeacherSubject({ ...studentInput, teacherUserId: "other-teacher", fullName: "Шевченко Марія", newGroupName: "КН-32" })).success).toBe(true);
  expect((await listStudentGroups()).map((group) => group.name)).toEqual(["КН-31", "КН-32"]);
  expect((await addStudentToTeacherSubject({ ...studentInput, fullName: "А", newGroupName: "Помилкова група" })).success).toBe(false);
  expect((await addStudentToTeacherSubject({ ...studentInput, groupMode: "existing", existingGroupName: "Неіснуюча" })).success).toBe(false);
  expect((await listStudentGroups()).length).toBe(2);
  expect((await addStudentToTeacherSubject(studentInput)).success).toBe(false);
  const students = await listGroupStudents();
  expect(students).toHaveLength(3);
  const anna = students.find((student) => student.fullName === "Ковальчук Анна")!;
  const bohdan = students.find((student) => student.fullName === "Мельник Богдан")!;
  const maria = students.find((student) => student.fullName === "Шевченко Марія")!;
  const draft = { subjectId: programming, roomId: rooms.find((room) => room.name === "101")!.id, classPeriodId: periods[0].id,
    lessonTypeId: (await listLessonTypes({ activeOnly: true }))[0].id,
    dayOfWeek: String(weekday), weekType: "both", groupNames: ["КН-31"], studentIds: [anna.id] };
  expect((await createLesson("teacher", "other-teacher", draft)).success).toBe(false);
  expect((await createLesson("teacher", "teacher", { ...draft, studentIds: [maria.id] })).success).toBe(false);
  expect((await createLesson("teacher", "teacher", { ...draft, studentIds: ["999999"] })).success).toBe(false);
  expect(await listTeacherLessons("teacher")).toHaveLength(0);
  const first = await createLesson("teacher", "teacher", draft);
  expect(first.success).toBe(true);
  const second = await createLesson("teacher", "teacher", { ...draft, classPeriodId: periods[1].id, studentIds: [bohdan.id] });
  expect(second.success).toBe(true);
  expect((await listTeacherStudents("teacher")).filter((student) => student.subjectId === programming)).toHaveLength(2);
  const findLesson = async (id: string) => (await listJournalLessons("teacher", date)).lessons.find((lesson) => lesson.lessonId === id)!;
  expect((await listJournalStudents("teacher", await findLesson(first.lessonId!))).map((student) => student.studentId)).toEqual([anna.id]);
  expect((await listJournalStudents("teacher", await findLesson(second.lessonId!))).map((student) => student.studentId)).toEqual([bohdan.id]);
  const conflict = await createLesson("teacher", "teacher", { ...draft, subjectId: math, groupNames: ["КН-32"], studentIds: [maria.id] });
  expect(conflict.success).toBe(false);
  expect(conflict.message).toContain("Заняття не створено");
  expect((await listTeacherStudents("teacher")).some((student) => student.studentId === maria.id)).toBe(false);
  expect((await createLesson("other-teacher", "other-teacher", draft)).success).toBe(false);
  expect((await createLesson("administrator", "other-teacher", { ...draft, classPeriodId: periods[2].id, roomId: rooms.find((room) => room.name === "102")!.id })).success).toBe(true);
  // Протилежні тижні дозволені, але «обидва» конфліктує з ними.
  expect((await createLesson("teacher", "teacher", { ...draft, classPeriodId: periods[3].id, weekType: "numerator" })).success).toBe(true);
  expect((await createLesson("teacher", "teacher", { ...draft, classPeriodId: periods[3].id, weekType: "denominator" })).success).toBe(true);
  expect((await createLesson("teacher", "teacher", { ...draft, classPeriodId: periods[3].id })).success).toBe(false);
  expect((await importTeacherStudents("teacher", { lessonId: first.lessonId! }, [{ fullName: maria.fullName, groupName: maria.groupName, subgroup: "2" }])).success).toBe(true);
  const roster = await listJournalStudents("teacher", await findLesson(first.lessonId!));
  expect(roster.map((student) => student.studentId).sort()).toEqual([anna.id, maria.id].sort());
  expect(await listJournalStudents("teacher", await findLesson(second.lessonId!))).toHaveLength(1);
  const lesson = await findLesson(first.lessonId!);
  expect((await saveAttendance("teacher", { date, key: lesson.key, version: 0, calendarToken: (await listJournalLessons("teacher", date)).day!.token, marks: roster.map((student) => ({ studentId: student.studentId, status: "present" })) })).success).toBe(true);
  await endSemester("administrator");
  expect((await listJournalLessons("teacher", date)).lessons[0].archived).toBe(true);
  expect(await listGroupStudents()).toHaveLength(3);
  expect(await listStudentGroups()).toHaveLength(2);
  const [links] = await sql`SELECT COUNT(*)::INT AS n FROM lesson_students` as unknown as { n: number }[];
  expect(links.n).toBe(0);
  // Початковий стан для ручного браузерного сценарію; лише тестова схема.
  await createLesson("teacher", "teacher", draft);
  await createLesson("teacher", "teacher", { ...draft, classPeriodId: periods[1].id, studentIds: [bohdan.id] });
}, 120000);
